### ISSUE TITLE
Broken endpoint

### ISSUE THREAD

**Issue by rossjones** [datagovuk/apiserver#71]
The endpoint at https://data.gov.uk/data/api/service is raising 500 errors.

```
14:46:50.731 [error] #PID<0.25773.52> running ApiServer.Endpoint terminated
Server: data.gov.uk:80 (http)
Request: GET /service
** (exit) an exception was raised:
    ** (ArgumentError) argument error
        (stdlib) :ets.match_object(:themes, :_)
        (stdlib) ets.erl:710: :ets.tab2list/1
        (api_server) lib/database/lookups.ex:65: Database.Lookups.find_all/1
        (api_server) web/controllers/api_controller.ex:34: ApiServer.ApiController.info/2
        (api_server) web/controllers/api_controller.ex:1: ApiServer.ApiController.phoenix_controller_pipeline/2
        (api_server) lib/phoenix/router.ex:265: ApiServer.Router.dispatch/2
        (api_server) web/router.ex:1: ApiServer.Router.do_call/2
        (api_server) lib/api_server/endpoint.ex:1: ApiServer.Endpoint.phoenix_pipeline/1
```

The error seems to be at `lib/database/lookups.ex:65`

**Comment by rossjones** [comment]
Fixed in f8b6b2bda66da7cc6007fb4afb03dad17f26f541 contrary to what CI says :(
